#!/bin/bash

packages=(
    accerciser
    avahi
    celluloid
    devhelp
    epiphany
    evolution
    evolution-data-server
    five-or-more
    flite
    four-in-a-row
    geary
    gnome-backgrounds
    gnome-builder
    gnome-calculator
    gnome-calendar
    gnome-characters
    gnome-chess
    gnome-clocks
    gnome-color-manager
    gnome-dictionary
    gnome-disk-utility
    gnome-font-viewer
    gnome-games
    gnome-icon-theme
    gnome-initial-setup
    gnome-keyring
    gnome-keyring-pkcs11:amd64
    gnome-klotski
    gnome-logs
    gnome-maps
    gnome-menus
    gnome-mines
    gnome-music
    gnome-nibbles
    gnome-online-accounts
    gnome-photos
    gnome-recipes
    gnome-reversi
    gnome-robots
    gnome-sound-recorder
    gnome-software
    gnome-software-common
    gnome-system-monitor
    gnome-taquin
    gnome-tetravex
    gnome-tour
    gnome-user-docs
    gnome-user-share
    gnome-video-effects
    gnome-weather
    gnome-2048
    gnome-accessibility-themes
    gnome-bluetooth-sendto
    gnome-browser-connector
    gnome-control-center
    gnome-font-viewer
    gnome-contacts
    gnome-disk-utility
    gnome-keyring
    gnome-keyring-pkcs11
    gnome-klotski
    gnome-logs
    gnome-maps
    gnome-menus
    gnome-mines
    gnome-music
    gnome-nibbles
    gnome-online-accounts
    gnome-photos
    gnome-recipes
    gnome-reversi
    gnome-sound-recorder
    gnome-software
    gnome-software-common
    gnome-system-monitor
    gnome-taquin
    gnome-tetravex
    gnome-tour
    gnome-user-docs
    gnome-user-share
    gnome-video-effects
    gnome-weather
    gnome-games
    modem-manager-gui
    malcontent
    mpv
    polari
    swell-foop
    yelp
    yelp-xsl
)

for pkg in "${packages[@]}"; do
    if pacman -Q "$pkg" &>/dev/null; then
        sudo pacman -Rns --noconfirm "$pkg" && echo "$pkg removed"
    else
        echo "$pkg not installed, skipping."
    fi
done
