#!/bin/bash

packages=(
    accerciser
    celluloid
    cheese
    devhelp
    endeavour
    epiphany
    evolution
    five-or-more
    flite
    four-in-a-row
    geary
    ghex
    gnome-backgrounds
    gnome-boxes
    gnome-builder
    gnome-calculator
    gnome-calendar
    gnome-characters
    gnome-chess
    gnome-clocks
    gnome-connections
    gnome-devel-docs
    gnome-dictionary
    gnome-disk-utility
    gnome-games
    gnome-initial-setup
    gnome-keyring-pkcs11:amd64
    gnome-klotski
    gnome-logs
    gnome-mahjongg
    gnome-maps
    gnome-menus
    gnome-mines
    gnome-multi-writer
    gnome-music
    gnome-nibbles
    gnome-photos
    gnome-recipes
    gnome-reversi
    gnome-robots
    gnome-sound-recorder
    gnome-software
    gnome-software-common
    gnome-system-monitor
    gnome-sudoku
    gnome-taquin
    gnome-text-editor
    gnome-tetravex
    gnome-tour
    gnome-user-docs
    gnome-user-share
    gnome-video-effects
    gnome-weather
    gnome-2048
    gnome-browser-connector
    gnome-contacts
    hitori
    lagno
    lightsoff
    modem-manager-gui
    malcontent
    mpv
    polari
    quadrapassel
    simple-scan
    swell-foop
    tali
    yelp-xsl
    yelp
)

for pkg in "${packages[@]}"; do
    if pacman -Q "$pkg" &>/dev/null; then
        sudo pacman -Rns --noconfirm "$pkg" && echo "$pkg removed"
    else
        echo "$pkg not installed, skipping."
    fi
done
